# Generated by Django 3.2.7 on 2021-09-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergyproducts',
            name='allergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.allergy'),
        ),
        migrations.AlterField(
            model_name='allergyproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nut'),
        ),
    ]
